### ISSUE TITLE
add containerized mon ,playbook failed 4.1-rhel-7

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#104] opened 2020-04-22 22:18 UTC
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-containerized-ceph-ansible-sanity-4.1-rhel7.8/15/console http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1587577640783/?C=M;O=A
```
TASK [ceph-container-common : set_fact image_repodigest_after_pulling] *********
task path: /usr/share/ceph-ansible/roles/ceph-container-common/tasks/fetch_image.yml:194
Wednesday 22 April 2020  15:00:02 -0400 (0:00:00.462)       0:02:33.770 ******* 

2020-04-22 14:57:47,973 - ceph.ceph - INFO - ok: [ceph-rhceph-jslave2-1587577640783-node2-monmds] => changed=false 
  ansible_facts:
    image_repodigest_after_pulling: sha256:24bf8efe8643927beb737c0a60790f41ea06d625c3c6dfd56974f7cc6b41bf65

2020-04-22 14:57:48,042 - ceph.ceph - INFO - ok: [ceph-rhceph-jslave2-1587577640783-node6-monrgw] => changed=false 
  ansible_facts:
    image_repodigest_after_pulling: sha256:24bf8efe8643927beb737c0a60790f41ea06d625c3c6dfd56974f7cc6b41bf65
fatal: [ceph-rhceph-jslave2-1587577640783-node1-monmgrinstaller]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: list object has no element 0
  
    The error appears to be in '/usr/share/ceph-ansible/roles/ceph-container-common/tasks/fetch_image.yml': line 194, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: set_fact image_repodigest_after_pulling
      ^ here

```

**Comment by XDsubhash** [comment] 2020-05-14 06:55
probably intermittent issue ,  update the issue if you see it frequently and add label script_issue

**Comment by Ameenasuhani** [comment] 2021-03-04 16:04
http://magna002.ceph.redhat.com/cephci-jenkins/archive/cephci-run-1606265487564/result.html the issue is not seen with ceph-ansible: 4.0.31-1.el7cp.noarch version. Closing this issue. Please feel free to reopen if you do think it's needed

**Closed by Ameenasuhani** 2021-03-04 16:04 UTC
Labels: Blocker, ceph-ansible, help wanted
