### ISSUE TITLE
Bug : Remove pool creation check after cmd execution in rbd_utils.py

### ISSUE THREAD

**Issue by pdhiran** [red-hat-storage/cephci#1292] opened 2022-03-16 18:45 UTC
With commit : https://github.com/red-hat-storage/cephci/pull/1272 , a check was added for pool creation, however this Could be removed as : 

1. In this instance, the command was run successfully,  but we received failure status and the test was stopped even though the pool was created with some delay. ( manually checked in the cluster, pool was present ) 

cmd execution: https://github.com/red-hat-storage/cephci/blob/4288086244b24a050c5728eb2a35751785adf509/tests/rbd/rbd_utils.py#L76

Test failure:
http://magna002.ceph.redhat.com/ceph-qe-logs/pawan/cephci-run-XZJVZD/
Rbd test failure : http://magna002.ceph.redhat.com/ceph-qe-logs/pawan/cephci-run-XZJVZD/rbd-io_0.log 

2. The pools are created with slight delay, hence to fix the issue, another PR was already submitted and merged. : https://github.com/red-hat-storage/cephci/pull/986 , where we recursively check pool creation status and return based on that.

Let me know what you guys think @VasishtaShastry @psathyan 

Pass log where the pool creation is recursively checked and then returns true.
```
2022-01-23 15:21:53,278 - ceph.ceph - INFO - Running command ceph osd pool create XvhJHrQFhW 64 64 on 10.0.211.29
2022-01-23 15:21:54,618 - ceph.ceph - INFO - Command completed successfully
2022-01-23 15:21:54,618 - ceph.ceph - INFO - Running command ceph df -f json on 10.0.211.29
2022-01-23 15:21:55,064 - ceph.ceph - INFO - Command completed successfully
2022-01-23 15:21:55,064 - tests.rbd.rbd_utils - ERROR - Pool:XvhJHrQFhW not populated yet
sleeping for 2 seconds and checking status again
2022-01-23 15:21:57,065 - ceph.ceph - INFO - Running command ceph df -f json on 10.0.211.29
2022-01-23 15:21:57,453 - ceph.ceph - INFO - Command completed successfully
2022-01-23 15:21:57,453 - tests.rbd.rbd_utils - INFO - pool XvhJHrQFhW exists in the cluster
```
log : http://magna002.ceph.redhat.com/ceph-qe-logs/pawan/cephci-run-ZMZJXT/rbd-io_0.log

**Comment by SrinivasaBharath** [comment] 2022-03-17 05:34
Failed with the same issue-http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-ZPPOH8

**Comment by psathyan** [comment] 2022-03-20 14:48
Any idea why there is a delay in creating a pool. If it is asynchronous call, we should revert #1272

**Comment by VasishtaShastry** [comment] 2022-03-31 13:48
Sorry, I had missed this issue

pull/1272 was raised as runs were failing with - unhandled TypeError in [check_pool_exists func](https://github.com/pdhiran/cephci/blob/8ab1e6c39cc5ff4a33a48a713d86f73f31b0cd4d/tests/rbd/rbd_utils.py#L107-L108)

Regression caused by pull/1272 has been addressed in https://github.com/red-hat-storage/cephci/pull/1306

**Closed by VasishtaShastry** 2022-03-31 13:48 UTC
Labels: RBD
